name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop, main ]

jobs:
  lint-app:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Lint code 🔍
        run: npx prettier --check src/

  build-app:
    needs: lint-app
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Build the site 🔨
        run: npm run build
